project_id = "saveabkhpaemynlfcgcy"

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.admin-user-actions]
verify_jwt = false

[functions.send-email-postmark]
verify_jwt = true

[functions.validate-license]
verify_jwt = false

[functions.license-activation]
verify_jwt = false

[functions.stripe-payment]
verify_jwt = true

[functions.create-crm-from-onboarding]
verify_jwt = true

[functions.track-download]
verify_jwt = false

[functions.upload-download-file]
verify_jwt = true

[functions.submit-contact-form]
verify_jwt = false