project_id = "saveabkhpaemynlfcgcy"

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.admin-user-actions]
verify_jwt = false

[functions.send-email-postmark]
verify_jwt = true

[functions.validate-license]
verify_jwt = false
